name: Lint & test & build & publish Docker image

on:
  workflow_dispatch:
  release:
    types: [released]

permissions:
  contents: write

jobs:
  lint-test:
    name: Lint & test
    uses: ./.github/workflows/digma-lint-test.yml

  build:
    name: Build
    needs: lint-test
    uses: ./.github/workflows/digma-build.yml

  attach-dist-asset:
    name: Attach release asset
    needs: build
    uses: ./.github/workflows/digma-release-asset.yml
    with:
      artifact-name: ${{ needs.build.outputs.dist-filename }}

  build-push-docker-image:
    name: Build & push Docker image
    needs: build
    uses: ./.github/workflows/digma-docker-image.yml
    secrets: inherit
    with:
      dist-artifact-name: ${{ needs.build.outputs.dist-filename }}
      push: true

  update-digma-ui:
    needs: [attach-dist-asset, build-push-docker-image]
    name: Update version in Digma UI
    runs-on: ubuntu-latests
    steps:
      - uses: actions/checkout@v4
      - name: Get Jaeger version
        run: echo "JAEGER_VERSION=$(jq -r '.version' jaeger.json)" >> $GITHUB_ENV

      - name: Get dist artifact version name
        id: get-dist-filename
        run: echo "dist-filename=$(cat ${{ needs.build.outputs.dist-filename }})" >> $GITHUB_ENV

      - run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.PAT }}" \
          https://api.github.com/repos/digma-ai/digma-ui/dispatches \
          -d '{
            "event_type": "update-jaeger",
            "client_payload": {
              "jaegerUIVersion": "'"${{ needs.build.outputs.version }}"'",
              "jaegerVersion": "'"${{ env.JAEGER_VERSION }}"'"
            }
          }'
