name: Lint & test & build

on:
  push:
    branches:
      - 'main'
    # Github Actions don't support YAML anchors yet, so we have to repeat
    # the paths-ignore in both push and pull_request events.
    # More info: https://github.com/actions/runner/issues/1182
    paths-ignore:
      - '.vscode/**'
      - '.prettierignore'
      - '.prettierrc'
      - '*.md'
      - 'DCO'
      - 'LICENSE'
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '.vscode/**'
      - '.prettierignore'
      - '.prettierrc'
      - '*.md'
      - 'DCO'
      - 'LICENSE'

jobs:
  lint-test:
    name: Lint & test
    uses: ./.github/workflows/digma-lint-test.yml

  build:
    name: Build
    needs: lint-test
    uses: ./.github/workflows/digma-build.yml

  build-docker-image:
    name: Build Docker image
    needs: build
    uses: ./.github/workflows/digma-docker-image.yml
    secrets: inherit
    with:
      dist-artifact-name: ${{ needs.build.outputs.artifact-name }}
      push: false
