name: Lint & test & build & publish Docker image

on:
  workflow_dispatch:
  release:
    types: [released]

permissions:
  contents: write

jobs:
  lint-test:
    name: Lint & test
    uses: ./.github/workflows/digma-lint-test.yml

  build:
    name: Build
    needs: lint-test
    uses: ./.github/workflows/digma-build.yml

  attach-release-asset:
    name: Attach release asset
    needs: build
    uses: ./.github/workflows/digma-release-asset.yml
    with:
      artifact-name: ${{ needs.build.outputs.artifact-name}}

  build-push-docker-image:
    name: Build & push Docker image
    needs: build
    uses: ./.github/workflows/digma-docker-image.yml
    secrets: inherit
    with:
      dist-artifact-name: ${{ needs.build.outputs.artifact-name }}
      push: true

  update-digma-ui:
    name: Update Jaeger dependencies in Digma UI
    needs: [build, attach-release-asset, build-push-docker-image]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Jaeger version
        run: echo "JAEGER_VERSION=$(jq -r '.version' jaeger.json)" >> $GITHUB_ENV

      - name: Dispatch event in digma-ui
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.RELEASE_PAT }}
          repository: digma-ai/digma-ui
          event-type: update-jaeger
          client-payload: |-
            {
              "jaegerUIVersion": "${{ needs.build.outputs.version }}",
              "jaegerVersion": "${{ env.JAEGER_VERSION }}"
            }
