name: Build

on:
  workflow_call:
    outputs:
      dist-filename:
        value: ${{ jobs.build.outputs.dist-filename }}
      version:
        value: ${{ jobs.build.outputs.version }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      dist-filename: ${{ steps.get-dist-filename.outputs.dist_filename }}
      version: ${{ steps.get-dist-filename.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        id: setup-node
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - run: yarn install --frozen-lockfile

      - run: yarn build

      - name: Get distributive filename and version
        id: get-dist-filename
        run: |
          git fetch --tags
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          FILENAME="dist-$LATEST_TAG.zip"
          echo "DIST_FILENAME=$FILENAME" >> $GITHUB_ENV
          echo "dist_filename=$FILENAME" >> $GITHUB_OUTPUT
          echo "version=${LATEST_TAG#v}" >> $GITHUB_OUTPUT

      - run: |
          cd packages/jaeger-ui/build
          zip -r ${{ env.DIST_FILENAME }} *

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.DIST_FILENAME }}
          path: packages/jaeger-ui/build/${{ env.DIST_FILENAME }}
