name: Publish Digma release

# Controls when the workflow will run
on:
  workflow_dispatch:
  release:
    types: [released]
  pull_request:

# permissions are needed if pushing to ghcr.io
permissions:
  packages: write

jobs:
  build:
    uses: digma-ai/digma-jaeger-ui/.github/workflows/reusable-push-to-docker.yml@feature/docker
    with:
      images: |
        digmatic/jaeger-ui
      tags: |
        type=schedule
        type=ref,event=branch
        type=ref,event=pr
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=semver,pattern={{major}}
        type=sha
        # set latest tag for digma branch
        type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'digma') }}
      dockerfile: ./Dockerfile
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
